"""
export_c.py — PyTorch model to C header exporter for STM32 embedded deployment.

Auto-detects network architecture from state dict.
Generates:
  - INT8 (q7_t) quantized weight arrays
  - Type-safe C inference function with correct dimensions
  - main_rule_fallback.h with BayesOpt constants

Architecture: common/export_c.py → generates firmware/ headers.
Bridges simulation (Python) ↔ embedded (C on STM32F103).
"""

import json
import os

import numpy as np


def float_to_q7(value: float, scale: float) -> int:
    """Convert float32 to int8 q7_t [-128, 127]."""
    return max(-128, min(127, int(round(value / scale))))


def _extract_linear_layers(state: dict) -> list[tuple[str, np.ndarray, np.ndarray]]:
    """Extract all Linear layer weight/bias pairs, sorted by sequential index.

    Returns list of (name, weight, bias) where name = 'fc0','fc1',...
    """
    layer_entries = []
    for key in state:
        if key.endswith(".weight"):
            # net.N.weight → extract N
            try:
                prefix = key.replace(".weight", "")
                idx = int(prefix.replace("net.", ""))
                layer_entries.append((idx, prefix))
            except ValueError:
                continue

    layer_entries.sort()  # sort by net index
    linear_layers = []
    for i, (_idx, prefix) in enumerate(layer_entries):
        w_key = f"{prefix}.weight"
        b_key = f"{prefix}.bias"
        if w_key in state and b_key in state:
            linear_layers.append((f"fc{i}", state[w_key].numpy(), state[b_key].numpy()))

    return linear_layers


def export_weights_as_c(
    model_path: str, output_dir: str = "firmware", layer_scales: list[float] | None = None
) -> str:
    """Export model weights as a C header with int8 quantized arrays and inference function.

    Args:
        model_path: Path to .pt checkpoint
        output_dir: Output directory
        layer_scales: Optional per-layer scale factors (auto-computed if None)

    Returns:
        Path to generated header
    """
    import torch

    ckpt = torch.load(model_path, map_location="cpu", weights_only=False)
    state = ckpt.get("state_dict", ckpt)

    os.makedirs(output_dir, exist_ok=True)
    basename = os.path.splitext(os.path.basename(model_path))[0]
    header_path = os.path.join(output_dir, f"{basename}_weights.h")

    layers = _extract_linear_layers(state)
    if not layers:
        raise ValueError("No Linear layers found in state dict")

    n_layers = len(layers)
    first_w = layers[0][1]
    last_w = layers[-1][1]
    input_dim = first_w.shape[1]
    output_dim = last_w.shape[0]

    # Hidden dimensions (all intermediate layers)
    hidden_dims = [layer[1].shape[0] for layer in layers[:-1]]

    # Architecture string
    dims_str = "→".join([str(input_dim)] + [str(d) for d in hidden_dims] + [str(output_dim)])
    guard = basename.upper() + "_WEIGHTS_H"

    lines = []
    lines.append("// Auto-generated by bottlesumo_pi/common/export_c.py")
    lines.append(f"// Source: {model_path}")
    lines.append(f"// Architecture: {dims_str} ({n_layers} Linear layers, q7_t int8)")
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define NANO_INPUT_DIM  {input_dim}")
    lines.append(f"#define NANO_OUTPUT_DIM {output_dim}")
    for i, d in enumerate(hidden_dims):
        lines.append(f"#define NANO_H{i}_DIM   {d}")
    lines.append("")

    # Quantize and write each layer
    quant_layers = []  # (name, q_weight, q_bias, w_shape, in_dim, out_dim)
    for name, weight, bias in layers:
        if layer_scales is None:
            max_w = max(abs(weight).max(), 1e-8)
            scale = max_w / 127.0
        else:
            scale = layer_scales.pop(0)

        w_q7 = np.array([float_to_q7(w, scale) for w in weight.flatten()], dtype=np.int8)
        b_q7 = np.array([float_to_q7(b, scale) for b in bias.flatten()], dtype=np.int8)

        w_shape = list(weight.shape)
        out_dim, in_dim = w_shape[0], w_shape[1]

        lines.append(f"// {name}: {in_dim}→{out_dim}, scale={scale:.6f}")
        lines.append(f"static const int8_t {name}_weight[{len(w_q7)}] = {{")
        # Chunk into rows of 16 values for readability
        for row_start in range(0, len(w_q7), 16):
            chunk = w_q7[row_start : row_start + 16]
            lines.append("    " + ", ".join(f"{v:4d}" for v in chunk) + ",")
        lines.append("};")
        lines.append(f"static const int8_t {name}_bias[{len(b_q7)}] = {{")
        b_chunks = [b_q7[i : i + 16] for i in range(0, len(b_q7), 16)]
        for chunk in b_chunks:
            lines.append("    " + ", ".join(f"{v:4d}" for v in chunk) + ",")
        lines.append("};")
        lines.append("")

        quant_layers.append((name, w_shape, in_dim, out_dim))

    # Generate inference function
    lines.append("// Quantized forward pass (q7_t → ReLU → ReLU → ... → q7_t)")
    lines.append("// Uses int32 accumulation with final >>7 requantization")
    lines.append("")
    lines.append("static inline void nano_inference(const int8_t *input, int8_t *output) {")

    # Track which hidden dim name was used last for accumulator declarations
    len(hidden_dims)

    for layer_i, (name, _w_shape, in_dim, out_dim) in enumerate(quant_layers):
        is_last = layer_i == n_layers - 1
        use_relu = not is_last

        if is_last:
            lines.append(f"    // Layer {layer_i}: {name} ({in_dim}→{out_dim}), linear output")
            lines.append(f"    for (int i = 0; i < {out_dim}; i++) {{")
        else:
            lines.append(f"    // Layer {layer_i}: {name} ({in_dim}→{out_dim}) + ReLU")
            # Declare hidden accumulators (int32 for first layer, int64 for deeper)
            acc_type = "int32_t" if layer_i == 0 else "int64_t"
            lines.append(f"    {acc_type} h{layer_i}[{out_dim}];")
            lines.append(f"    for (int i = 0; i < {out_dim}; i++) {{")

        lines.append(f"        int64_t sum = (int64_t){name}_bias[i];")
        lines.append(f"        for (int j = 0; j < {in_dim}; j++) {{")
        if layer_i == 0:
            lines.append(
                f"            sum += (int64_t)input[j] * (int64_t){name}_weight[i*{in_dim} + j];"
            )
        else:
            prev_h = f"h{layer_i - 1}"
            lines.append(
                f"            sum += (int64_t){prev_h}[j] * (int64_t){name}_weight[i*{in_dim} + j];"
            )

        lines.append("        }")

        if use_relu:
            lines.append(f"        h{layer_i}[i] = (sum > 0) ? sum : 0;  // ReLU")
        else:
            lines.append("        output[i] = (int8_t)(sum >> 7);  // re-quantize")
        lines.append("    }")
        if not is_last:
            lines.append("")

    lines.append("}")
    lines.append("")
    lines.append(f"#endif // {guard}")

    with open(header_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    total_bytes = sum(len(layer[1].flatten()) + len(layer[2].flatten()) for layer in layers)
    print(f"  Generated: {os.path.abspath(header_path)}")
    print(f"  Architecture: {dims_str}")
    print(f"  Total parameters: {total_bytes} bytes (int8)")
    print(f"  Lines: {len(lines)}")
    return header_path


def export_config_as_c(config_path: str = None, output_dir: str = "firmware") -> str:
    """Generate main_rule_fallback.h with optimal BayesOpt configuration."""
    if config_path is None:
        config_path = os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "..",
            "simulation",
            "evaluation",
            "optimal_config.json",
        )

    if not os.path.exists(config_path):
        print(f"WARNING: {config_path} not found, using defaults")
        params = {
            "push_threshold": {"value": 0.285, "description": "Edge push threshold"},
            "edge_penalty_weight": {
                "value": 5.0,
                "description": "Edge penalty weight (corrected from 71.59)",
            },
            "action_bins": {"value": 20, "description": "Number of action bins"},
            "target_update_freq": {"value": 400, "description": "Target network update frequency"},
        }
    else:
        with open(config_path, encoding="utf-8") as f:
            cfg = json.load(f)
        params = cfg.get("parameters", cfg)

    os.makedirs(output_dir, exist_ok=True)
    header_path = os.path.join(output_dir, "main_rule_fallback.h")

    lines = []
    lines.append("// Auto-generated by bottlesumo_pi/common/export_c.py")
    lines.append("// Source: Meta-Harness Bayesian Optimization")
    lines.append("#ifndef MAIN_RULE_FALLBACK_H")
    lines.append("#define MAIN_RULE_FALLBACK_H")
    lines.append("")

    for name, cfg in params.items():
        desc = cfg if isinstance(cfg, str) else cfg.get("description", name)
        val = cfg if isinstance(cfg, (int, float)) else cfg.get("value", cfg)
        lines.append(f"// {desc}")
        if isinstance(val, float):
            lines.append(f"#define {name.upper()} {val}f")
        else:
            lines.append(f"#define {name.upper()} {val}")
        lines.append("")

    lines.append("// Fixed parameters (confirmed by causal SCM)")
    lines.append("#define USE_DOUBLE_DQN      1")
    lines.append("#define USE_DUELING         0")
    lines.append("#define USE_ACTION_MASKING  0")
    lines.append("#define USE_CURRICULUM      1")
    lines.append("#define USE_DISTILLATION    1")
    lines.append("#define DISTILL_TEMP         4.0f")
    lines.append("#define DISTILL_ALPHA        0.5f")
    lines.append("")
    lines.append("#endif // MAIN_RULE_FALLBACK_H")

    with open(header_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"  Generated: {os.path.abspath(header_path)} ({len(lines)} lines)")
    return header_path


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Export model weights as C header")
    parser.add_argument(
        "--model", type=str, default="models/nano_student.pt", help="Path to model checkpoint"
    )
    parser.add_argument("--output-dir", type=str, default="firmware", help="Output directory")
    parser.add_argument("--config-only", action="store_true", help="Only generate config header")
    args = parser.parse_args()

    export_config_as_c(output_dir=args.output_dir)

    if not args.config_only and os.path.exists(args.model):
        export_weights_as_c(args.model, output_dir=args.output_dir)
    elif not args.config_only:
        print(f"Model not found: {args.model}, skipping weight export")


if __name__ == "__main__":
    main()
