# -*- coding: utf-8 -*-
"""P11: codegen tests — generated matchers are real, deterministic and
behaviorally equivalent to the runtime policy engine (src/policy.py)."""

import importlib.util
import json
import shutil
from pathlib import Path

import pytest

from src.codegen.generator import generate
from src.policy import PolicyEngine

REPO_ROOT = Path(__file__).resolve().parent.parent
POLICY = REPO_ROOT / "config" / "policies.yaml"
GENERATED = REPO_ROOT / "src" / "codegen" / "_generated_matches.py"


def _load_generated(path: Path = GENERATED):
    spec = importlib.util.spec_from_file_location("_generated_matches", path)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _engine_first(engine, path, method, tool_names=None):
    body = None
    if tool_names is not None:
        body = json.dumps({"tools": [{"function": {"name": t}} for t in tool_names]})
    for rule in engine.rules:
        if rule.matches(path, method, body):
            return (rule.name, rule.action)
    return None


# (label, path, method, tool_names)
CASES = [
    ("glob delete", "/api/delete/x", "POST", None),
    ("exact delete (no child)", "/api/delete", "POST", None),
    ("sudo", "/api/admin/sudo", "POST", None),
    ("config write", "/api/config/app", "POST", None),
    ("model update", "/api/model/update", "POST", None),
    ("chat allow", "/api/chat", "POST", None),
    ("query allow", "/api/query", "GET", None),
    ("health allow", "/health", "GET", None),
    ("shell tool", "/api/chat", "POST", ["bash"]),
    ("shell tool 2", "/api/chat", "POST", ["python_exec"]),
    ("file write tool", "/api/chat", "POST", ["write_file"]),
    ("file delete tool", "/api/chat", "POST", ["delete_file"]),
    ("no tools", "/api/chat", "POST", []),
    ("unknown tool", "/api/chat", "POST", ["read_file"]),
    ("wrong method", "/api/chat", "GET", None),
    ("unmatched path", "/api/decisions", "GET", None),
]


class TestGeneratedArtifact:
    def test_artifact_exists_and_imports(self):
        assert GENERATED.exists(), "run python -m src.codegen.generator first"
        mod = _load_generated()
        assert callable(mod.match_any)

    def test_do_not_edit_header(self):
        head = GENERATED.read_text(encoding="utf-8").splitlines()[0]
        assert "DO NOT EDIT" in head
        assert "generated by src/codegen/generator" in head

    def test_one_matcher_per_rule(self):
        import yaml

        rules = yaml.safe_load(POLICY.read_text(encoding="utf-8"))["rules"]
        mod = _load_generated()
        assert len(mod._MATCHERS) == len(rules) == len(mod._ORDER)
        assert set(mod._MATCHERS) == {r["name"] for r in rules}

    def test_regeneration_is_idempotent(self, tmp_path):
        out = tmp_path / "gm.py"
        w1, _ = generate(POLICY, out)
        w2, _ = generate(POLICY, out)
        assert w1 and not w2, "second run must be a no-op (idempotent)"
        assert out.read_text(encoding="utf-8") == GENERATED.read_text(encoding="utf-8"), (
            "committed artifact drifted from regenerated output — "
            "rerun python -m src.codegen.generator"
        )


class TestGeneratedSemantics:
    @pytest.fixture(scope="class")
    def gen(self):
        return _load_generated()

    @pytest.mark.parametrize("label,path,method,tools", CASES, ids=[c[0] for c in CASES])
    def test_semantics(self, gen, label, path, method, tools):
        r = gen.match_any(path=path, method=method, tool_names=tools)
        if label in ("exact delete (no child)", "wrong method", "unmatched path"):
            assert r is None, f"{label}: expected no match, got {r}"
        else:
            assert r is not None and r[1] in ("ALLOW", "DENY", "ESCALATE"), f"{label}: {r}"

    def test_priority_order(self, gen):
        r = gen.match_any(path="/api/chat", method="POST", tool_names=["delete_file", "bash"])
        # DENY (block-shell-tool, prio 10) must beat ESCALATE (prio 20) for the
        # same request, regardless of tool order in the payload.
        assert r[0] == "block-shell-tool" and r[1] == "DENY"

    def test_glob_vs_exact(self, gen):
        assert gen.match_any(path="/api/delete/x", method="POST")[0] == "block-delete"
        assert gen.match_any(path="/api/delete", method="POST") is None


class TestRuntimeEquivalence:
    """The decisive claim: generated code == runtime policy semantics."""

    @pytest.fixture(scope="class")
    def both(self):
        gen = _load_generated()
        engine = PolicyEngine(str(POLICY))
        return gen, engine

    @pytest.mark.parametrize("label,path,method,tools", CASES, ids=[c[0] for c in CASES])
    def test_generated_equals_runtime(self, both, label, path, method, tools):
        gen, engine = both
        g = gen.match_any(path=path, method=method, tool_names=tools)
        e = _engine_first(engine, path, method, tools)
        g_pair = None if g is None else (g[0], g[1])
        assert g_pair == e, (
            f"{label}: generated {g_pair} != runtime {e} — codegen drifted "
            f"from src/policy.py semantics"
        )
