# -*- coding: utf-8 -*-
"""P11: YAML→Python 匹配函数生成器（编译式自生成）。

从 ``config/policies.yaml`` 编译出可执行的匹配函数模块
（``src/codegen/_generated_matches.py``）：

* 每条规则 -> 一个 ``match_<name>(path, method, tool_names)`` 函数；
* 主入口 ``match_any(...)`` 按 priority 升序返回首个命中
  ``(rule_name, action, reason, priority)``；
* 确定性 + 幂等：同输入同输出；写文件前逐字节比较，无变化则跳过。

诚实边界（META_CAPABILITIES "自生成"的声明依据）：
这是「声明式策略 -> 可执行匹配函数」的**编译式生成**（约 90 行），
不是 LLM 任意代码合成；生成的代码不替换运行时启发式
（``src/danger.py`` 的 DANGEROUS_PREFIXES / DANGEROUS_TOOL_NAMES 仍是
运行时的第一道闸），而是作为可独立验证的策略语义产物存在。

用法:
    python -m src.codegen.generator --policy config/policies.yaml [--out src/codegen/_generated_matches.py]
"""

import argparse
import importlib.util
import os
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import yaml

GENERATED_HEADER = (
    "# DO NOT EDIT -- generated by src/codegen/generator.py from {policy}\n"
    "# Regenerate: python -m src.codegen.generator --policy {policy}\n"
    "# Deterministic + idempotent: identical input -> identical bytes.\n"
)


def _escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _ident(name: str) -> str:
    """Normalize a rule name into a legal Python identifier.

    YAML rule names may contain dashes ("block-delete"); the generated
    matcher function is named match_block_delete while the _MATCHERS key
    keeps the original rule name so match_any returns the YAML rule name.
    """
    return re.sub(r"\W", "_", name)


def _rel_posix(p: Path) -> str:
    """Path relative to CWD (fallback: absolute) — keeps generated headers
    byte-identical across machines/CI when the policy is under the repo."""
    try:
        return os.path.relpath(p, Path.cwd()).replace("\\", "/")
    except ValueError:  # different drive on Windows
        return p.as_posix()


def _render_path_match(rule: Dict[str, Any]) -> str:
    """Render a path-pattern matcher equivalent to src/policy.py::_path_matches.

    Runtime semantics (src/policy.py:277-286):
      1. exact equality on normalized path;
      2. if pattern contains '*', regex ^...$ with '*' -> '.*';
      3. if pattern ends with '/', prefix match.
    The generated code mirrors these three branches exactly so the generated
    module is behaviorally equivalent to the runtime policy engine.
    """
    pattern = rule.get("path_pattern", "/")
    method = rule.get("method", "POST")
    pat = _escape(pattern)
    return (
        f'    if method != "{method}":\n'
        "        return False\n"
        "    if not path:\n"
        "        return False\n"
        "    import posixpath\n"
        '    normalized = posixpath.normpath(path.split("?", 1)[0])\n'
        f'    if "{pat}" == normalized:\n'
        "        return True\n"
        f'    if "*" in "{pat}":\n'
        f'        _pattern = "^" + re.escape("{pat}").replace(r"\\*", ".*") + "$"\n'
        "        return bool(re.match(_pattern, normalized))\n"
        f'    if "{pat}".endswith("/") and normalized.startswith("{pat}"):\n'
        "        return True\n"
        "    return False\n"
    )


def _render_json_match(rule: Dict[str, Any]) -> str:
    """Render a json_path matcher equivalent to src/policy.py::_json_rule_matches.

    Runtime semantics: any extracted value matching json_pattern via re.search
    (src/policy.py:275). Tool-name rules also carry a method guard (POST).
    """
    method = rule.get("method", "POST")
    json_pattern = rule.get("json_pattern", "")
    pat = _escape(json_pattern)
    return (
        f'    if method != "{method}":\n'
        "        return False\n"
        "    if not tool_names:\n"
        "        return False\n"
        f'    _re = re.compile(r"{pat}")  # noqa: policy (codegen from policies.yaml)\n'
        "    return any(_re.search(t) for t in tool_names)\n"
    )


def _render_rule_fn(rule: Dict[str, Any]) -> str:
    name = rule.get("name", "rule")
    fname = _ident(name)
    has_json = bool(rule.get("json_path") and rule.get("json_pattern"))
    body = _render_json_match(rule) if has_json else _render_path_match(rule)
    return (
        f"def match_{fname}(path, method, tool_names=None):\n"
        f'    """Generated matcher for rule "{name}" '
        f'(action={rule.get("action")}, priority={rule.get("priority")})."""\n'
        f"{body}\n"
    )


def generate(policy_path: Path, out_path: Path) -> Tuple[bool, List[str]]:
    """Compile policies.yaml -> generated Python module.

    Returns (written, [diagnostics]); ``written=True`` iff the file changed.
    """
    data = yaml.safe_load(policy_path.read_text(encoding="utf-8"))
    rules: List[Dict[str, Any]] = data.get("rules", [])
    if not rules:
        raise ValueError(f"{policy_path}: no 'rules' found")

    fn_src: List[str] = []
    matchers: List[str] = []
    actions: List[str] = []
    reasons: List[str] = []
    priorities: List[str] = []
    for rule in rules:
        name = rule["name"]
        fname = _ident(name)
        fn_src.append(_render_rule_fn(rule))
        matchers.append(f'    "{name}": match_{fname},')
        actions.append(f'    "{name}": "{_escape(str(rule.get("action")))}",')
        reasons.append(f'    "{name}": "{_escape(str(rule.get("reason", "")))}",')
        priorities.append(f'    "{name}": {int(rule.get("priority", 100))},')

    order = sorted(rules, key=lambda r: int(r.get("priority", 100)))
    order_names = [r["name"] for r in order]

    policy_rel = _rel_posix(policy_path)
    src = GENERATED_HEADER.format(policy=policy_rel)
    src += (
        "\nimport re\n"
        "from typing import Any, Optional\n\n\n"
        + "\n\n".join(fn_src)
        + "\n\n\n"
        "_MATCHERS: dict[str, Any] = {\n"
        + "\n".join(matchers)
        + "\n}\n\n"
        "_ACTIONS: dict[str, str] = {\n"
        + "\n".join(actions)
        + "\n}\n\n"
        "_REASONS: dict[str, str] = {\n"
        + "\n".join(reasons)
        + "\n}\n\n"
        "_PRIORITY: dict[str, int] = {\n"
        + "\n".join(priorities)
        + "\n}\n\n"
        "_ORDER: list[str] = [\n"
        + "".join(f'    "{n}",\n' for n in order_names)
        + "]\n\n\n"
        "def match_any(path=None, method=None, tool_names=None):\n"
        '    """Return (rule_name, action, reason, priority) of the first\n'
        '    matching rule in priority order, or None if nothing matches."""\n'
        "    for name in _ORDER:\n"
        "        if _MATCHERS[name](path, method, tool_names):\n"
        "            return (name, _ACTIONS[name], _REASONS[name], _PRIORITY[name])\n"
        "    return None\n"
    )

    written = False
    if out_path.exists():
        old = out_path.read_text(encoding="utf-8")
        if old == src:
            return written, [f"{out_path.name}: unchanged (idempotent)"]
    # 固定 LF 输出: 文本模式在 Windows 会写成 CRLF, 导致同一输入在不同平台
    # 产生不同字节 (CI drift 根因) —— 显式 newline="\n" 保证跨平台字节确定性
    out_path.write_text(src, encoding="utf-8", newline="\n")
    written = True
    return written, [f"{out_path.name}: generated ({len(rules)} rules -> {len(fn_src)} matchers)"]


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="P11 YAML->Python matcher codegen")
    ap.add_argument("--policy", default="config/policies.yaml")
    ap.add_argument("--out", default="src/codegen/_generated_matches.py")
    args = ap.parse_args(argv)

    written, diags = generate(Path(args.policy), Path(args.out))
    for d in diags:
        print(f"codegen: {d}")

    # verify the generated module imports and smoke-tests (fail-closed)
    spec = importlib.util.spec_from_file_location("_generated_matches", Path(args.out))
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    probe = mod.match_any(path="/api/chat", method="POST", tool_names=["bash"])
    if probe is None or probe[1] not in ("ALLOW", "DENY", "ESCALATE"):
        print("codegen: FAIL -- generated module smoke-test failed")
        return 1
    print(f"codegen: smoke-test OK -- first match for (chat, [bash]) = {probe[0]}:{probe[1]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
