# DO NOT EDIT -- generated by src/codegen/generator.py from config/policies.yaml
# Regenerate: python -m src.codegen.generator --policy config/policies.yaml
# Deterministic + idempotent: identical input -> identical bytes.

import re
from typing import Any, Optional


def match_block_delete(path, method, tool_names=None):
    """Generated matcher for rule "block-delete" (action=DENY, priority=10)."""
    if method != "POST":
        return False
    if not path:
        return False
    import posixpath
    normalized = posixpath.normpath(path.split("?", 1)[0])
    if "/api/delete/*" == normalized:
        return True
    if "*" in "/api/delete/*":
        _pattern = "^" + re.escape("/api/delete/*").replace(r"\*", ".*") + "$"
        return bool(re.match(_pattern, normalized))
    if "/api/delete/*".endswith("/") and normalized.startswith("/api/delete/*"):
        return True
    return False



def match_block_sudo(path, method, tool_names=None):
    """Generated matcher for rule "block-sudo" (action=DENY, priority=10)."""
    if method != "POST":
        return False
    if not path:
        return False
    import posixpath
    normalized = posixpath.normpath(path.split("?", 1)[0])
    if "/api/admin/sudo" == normalized:
        return True
    if "*" in "/api/admin/sudo":
        _pattern = "^" + re.escape("/api/admin/sudo").replace(r"\*", ".*") + "$"
        return bool(re.match(_pattern, normalized))
    if "/api/admin/sudo".endswith("/") and normalized.startswith("/api/admin/sudo"):
        return True
    return False



def match_escalate_config_write(path, method, tool_names=None):
    """Generated matcher for rule "escalate-config-write" (action=ESCALATE, priority=20)."""
    if method != "POST":
        return False
    if not path:
        return False
    import posixpath
    normalized = posixpath.normpath(path.split("?", 1)[0])
    if "/api/config/*" == normalized:
        return True
    if "*" in "/api/config/*":
        _pattern = "^" + re.escape("/api/config/*").replace(r"\*", ".*") + "$"
        return bool(re.match(_pattern, normalized))
    if "/api/config/*".endswith("/") and normalized.startswith("/api/config/*"):
        return True
    return False



def match_escalate_model_update(path, method, tool_names=None):
    """Generated matcher for rule "escalate-model-update" (action=ESCALATE, priority=20)."""
    if method != "POST":
        return False
    if not path:
        return False
    import posixpath
    normalized = posixpath.normpath(path.split("?", 1)[0])
    if "/api/model/update" == normalized:
        return True
    if "*" in "/api/model/update":
        _pattern = "^" + re.escape("/api/model/update").replace(r"\*", ".*") + "$"
        return bool(re.match(_pattern, normalized))
    if "/api/model/update".endswith("/") and normalized.startswith("/api/model/update"):
        return True
    return False



def match_allow_chat(path, method, tool_names=None):
    """Generated matcher for rule "allow-chat" (action=ALLOW, priority=100)."""
    if method != "POST":
        return False
    if not path:
        return False
    import posixpath
    normalized = posixpath.normpath(path.split("?", 1)[0])
    if "/api/chat" == normalized:
        return True
    if "*" in "/api/chat":
        _pattern = "^" + re.escape("/api/chat").replace(r"\*", ".*") + "$"
        return bool(re.match(_pattern, normalized))
    if "/api/chat".endswith("/") and normalized.startswith("/api/chat"):
        return True
    return False



def match_allow_query(path, method, tool_names=None):
    """Generated matcher for rule "allow-query" (action=ALLOW, priority=100)."""
    if method != "GET":
        return False
    if not path:
        return False
    import posixpath
    normalized = posixpath.normpath(path.split("?", 1)[0])
    if "/api/query" == normalized:
        return True
    if "*" in "/api/query":
        _pattern = "^" + re.escape("/api/query").replace(r"\*", ".*") + "$"
        return bool(re.match(_pattern, normalized))
    if "/api/query".endswith("/") and normalized.startswith("/api/query"):
        return True
    return False



def match_allow_health(path, method, tool_names=None):
    """Generated matcher for rule "allow-health" (action=ALLOW, priority=200)."""
    if method != "GET":
        return False
    if not path:
        return False
    import posixpath
    normalized = posixpath.normpath(path.split("?", 1)[0])
    if "/health" == normalized:
        return True
    if "*" in "/health":
        _pattern = "^" + re.escape("/health").replace(r"\*", ".*") + "$"
        return bool(re.match(_pattern, normalized))
    if "/health".endswith("/") and normalized.startswith("/health"):
        return True
    return False



def match_block_shell_tool(path, method, tool_names=None):
    """Generated matcher for rule "block-shell-tool" (action=DENY, priority=10)."""
    if method != "POST":
        return False
    if not tool_names:
        return False
    _re = re.compile(r"^(execute_command|system_run|shell_exec|terminal_exec|run_shell|bash|python_exec)$")  # noqa: policy (codegen from policies.yaml)
    return any(_re.search(t) for t in tool_names)



def match_escalate_file_write_tool(path, method, tool_names=None):
    """Generated matcher for rule "escalate-file-write-tool" (action=ESCALATE, priority=20)."""
    if method != "POST":
        return False
    if not tool_names:
        return False
    _re = re.compile(r"^(write_file|edit_file|append_file|create_file|overwrite_file|delete_file|rm_file|set_secret|set_env)$")  # noqa: policy (codegen from policies.yaml)
    return any(_re.search(t) for t in tool_names)




_MATCHERS: dict[str, Any] = {
    "block-delete": match_block_delete,
    "block-sudo": match_block_sudo,
    "escalate-config-write": match_escalate_config_write,
    "escalate-model-update": match_escalate_model_update,
    "allow-chat": match_allow_chat,
    "allow-query": match_allow_query,
    "allow-health": match_allow_health,
    "block-shell-tool": match_block_shell_tool,
    "escalate-file-write-tool": match_escalate_file_write_tool,
}

_ACTIONS: dict[str, str] = {
    "block-delete": "DENY",
    "block-sudo": "DENY",
    "escalate-config-write": "ESCALATE",
    "escalate-model-update": "ESCALATE",
    "allow-chat": "ALLOW",
    "allow-query": "ALLOW",
    "allow-health": "ALLOW",
    "block-shell-tool": "DENY",
    "escalate-file-write-tool": "ESCALATE",
}

_REASONS: dict[str, str] = {
    "block-delete": "删除操作在生产环境被禁止",
    "block-sudo": "sudo 操作被全局禁止",
    "escalate-config-write": "配置修改需要人工审批",
    "escalate-model-update": "模型更新需要人工审批",
    "allow-chat": "标准聊天请求，放行",
    "allow-query": "标准查询请求，放行",
    "allow-health": "健康检查端点，放行",
    "block-shell-tool": "LLM 请求声明系统级工具 (shell/命令执行) — 拒绝 (json_path 治理)",
    "escalate-file-write-tool": "LLM 请求声明文件写/删或敏感配置工具 — 升级人工审批 (json_path 治理)",
}

_PRIORITY: dict[str, int] = {
    "block-delete": 10,
    "block-sudo": 10,
    "escalate-config-write": 20,
    "escalate-model-update": 20,
    "allow-chat": 100,
    "allow-query": 100,
    "allow-health": 200,
    "block-shell-tool": 10,
    "escalate-file-write-tool": 20,
}

_ORDER: list[str] = [
    "block-delete",
    "block-sudo",
    "block-shell-tool",
    "escalate-config-write",
    "escalate-model-update",
    "escalate-file-write-tool",
    "allow-chat",
    "allow-query",
    "allow-health",
]


def match_any(path=None, method=None, tool_names=None):
    """Return (rule_name, action, reason, priority) of the first
    matching rule in priority order, or None if nothing matches."""
    for name in _ORDER:
        if _MATCHERS[name](path, method, tool_names):
            return (name, _ACTIONS[name], _REASONS[name], _PRIORITY[name])
    return None
