"""
export_to_c.py — Export HybridAgent (StrategyDQN + ConditionalActor) to C arrays

Produces:
    stm32_weights.h      — float arrays for all weights and biases
    stm32_model_info.h   — layer dimensions and architecture

Usage:
    python export_to_c.py --model models/hybrid_final.pt --out stm32_deploy/
    python export_to_c.py --random  (generates random weights for testing)
"""
from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent.resolve()))  # conversation root
# Lazy import: only needed when loading trained models


def format_float(value: float) -> str:
    """Format float for C array with sufficient precision."""
    return f"{value:.10f}f"


def generate_random_weights() -> dict:
    """Generate a dummy model with random weights for testing."""
    from bottlesumo_pi.common.hybrid_agent import HybridAgent, HybridConfig
    cfg = HybridConfig()
    agent = HybridAgent(cfg)
    return {
        "strategy_dqn": agent.strategy_dqn.state_dict(),
        "actor": agent.actor.state_dict(),
    }


def export_layer_weights(prefix: str, weight: torch.Tensor, bias: torch.Tensor,
                         w_name: str, b_name: str) -> list[str]:
    """Export one linear layer to C arrays."""
    w = weight.cpu().numpy()
    b = bias.cpu().numpy()
    out_dim, in_dim = w.shape

    lines = [f"// {prefix}: {in_dim} → {out_dim}"]
    lines.append(f"#define {w_name}_IN  {in_dim}")
    lines.append(f"#define {w_name}_OUT {out_dim}")

    # Weights (row-major: weight[out][in])
    lines.append(f"static const float _{w_name}[{out_dim * in_dim}] = {{")
    for i in range(out_dim):
        row_vals = ", ".join(format_float(v) for v in w[i])
        lines.append(f"    /* row {i:2d} */ {row_vals},")
    lines.append("};")

    # Bias
    lines.append(f"static const float _{b_name}[{out_dim}] = {{")
    lines.append("    " + ", ".join(format_float(v) for v in b))
    lines.append("};")

    return lines


def export_embedding(name: str, weight: torch.Tensor) -> list[str]:
    """Export embedding layer (vocab × dim) to C arrays."""
    w = weight.cpu().numpy()
    vocab, dim = w.shape
    lines = [f"// Embedding: {vocab} × {dim}"]
    lines.append(f"#define {name}_VOCAB {vocab}")
    lines.append(f"#define {name}_DIM   {dim}")
    lines.append(f"static const float _{name}[{vocab * dim}] = {{")
    for i in range(vocab):
        row_vals = ", ".join(format_float(v) for v in w[i])
        lines.append(f"    /* idx {i} */ {row_vals},")
    lines.append("};")
    return lines


def generate_header(weights: dict, action_bounds: tuple) -> str:
    """Generate complete stm32_weights.h."""
    lines = [
        "/* Auto-generated by export_to_c.py — DO NOT EDIT */",
        "/* BottleSumo V11 HybridAgent → STM32 C arrays */",
        "",
        "#ifndef STM32_WEIGHTS_H",
        "#define STM32_WEIGHTS_H",
        "",
        "// ── Action Bounds ──",
        f"#define ACTION_LINEAR_LOW   {action_bounds[0]:.4f}f",
        f"#define ACTION_LINEAR_HIGH  {action_bounds[1]:.4f}f",
        f"#define ACTION_ANGULAR_LOW  {action_bounds[2]:.4f}f",
        f"#define ACTION_ANGULAR_HIGH {action_bounds[3]:.4f}f",
        "",
        "// ═══ Strategy DQN (7→128→128→4) ═══",
    ]

    sd = weights["strategy_dqn"]
    # Layer 0: 7→128
    lines.extend(export_layer_weights("DQN L0", sd["net.0.weight"], sd["net.0.bias"],
                                       "DQN_L0_W", "DQN_L0_B"))
    # Layer 1: 128→128
    lines.extend(export_layer_weights("DQN L1", sd["net.2.weight"], sd["net.2.bias"],
                                       "DQN_L1_W", "DQN_L1_B"))
    # Layer 2: 128→4
    lines.extend(export_layer_weights("DQN L2", sd["net.4.weight"], sd["net.4.bias"],
                                       "DQN_L2_W", "DQN_L2_B"))

    lines.extend([
        "",
        "// ═══ Conditional TD3 Actor ═══",
        f"// Input: state(7) + strategy_emb(4) = 11",
    ])

    act = weights["actor"]
    # Embedding
    lines.extend(export_embedding("ACTOR_EMB", act["strategy_embedding.weight"]))
    # Layer 0: 11→256
    lines.extend(export_layer_weights("Actor L0", act["net.0.weight"], act["net.0.bias"],
                                       "ACTOR_L0_W", "ACTOR_L0_B"))
    # Layer 1: 256→256
    lines.extend(export_layer_weights("Actor L1", act["net.2.weight"], act["net.2.bias"],
                                       "ACTOR_L1_W", "ACTOR_L1_B"))
    # Layer 2: 256→2
    lines.extend(export_layer_weights("Actor L2", act["net.4.weight"], act["net.4.bias"],
                                       "ACTOR_L2_W", "ACTOR_L2_B"))

    lines.extend([
        "",
        f"#define MAX_ACTION 1.0f",
        "",
        "#endif /* STM32_WEIGHTS_H */",
    ])

    return "\n".join(lines)


def verify_export(agent: HybridAgent, header_path: str):
    """Verify C arrays match PyTorch weights."""
    # Just print summary statistics
    sd = agent.strategy_dqn.state_dict()
    for key, val in sd.items():
        v = val.cpu().numpy()
        print(f"  DQN {key:20s}: shape={list(v.shape)}  range=[{v.min():.4f}, {v.max():.4f}]")

    act = agent.actor.state_dict()
    for key, val in act.items():
        v = val.cpu().numpy()
        print(f"  Actor {key:20s}: shape={list(v.shape)}  range=[{v.min():.4f}, {v.max():.4f}]")


if __name__ == "__main__":
    p = argparse.ArgumentParser(description="Export HybridAgent to C arrays for STM32")
    p.add_argument("--model", type=str, default=None, help="Path to trained .pt model")
    p.add_argument("--random", action="store_true", help="Generate random weights (no trained model)")
    p.add_argument("--out", type=str, default="stm32_deploy")
    args = p.parse_args()

    if args.model and Path(args.model).exists():
        print(f"Loading model: {args.model}")
        cfg = HybridConfig()
        agent = HybridAgent(cfg)
        agent.load(args.model)
        weights = {"strategy_dqn": agent.strategy_dqn.state_dict(),
                   "actor": agent.actor.state_dict()}
    else:
        print("Generating random weights (no trained model specified)")
        weights = generate_random_weights()

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Action bounds for continuous env
    action_bounds = (-0.7, 0.7, -5.0, 5.0)  # linear_low, linear_high, angular_low, angular_high

    header = generate_header(weights, action_bounds)

    (out_dir / "stm32_weights.h").write_text(header, encoding="utf-8")
    print(f"Generated: {out_dir / 'stm32_weights.h'} ({len(header)} bytes)")

    # Generate model info
    total_params = 7*128 + 128 + 128*128 + 128 + 128*4 + 4 + (7+4)*256 + 256 + 256*256 + 256 + 256*2 + 2 + 4*4 + 4
    info = f"""/* Auto-generated model info */
#define STATE_DIM 7
#define N_STRATEGIES 4
#define ACTOR_EMBEDDING_DIM 4

/* DQN Architecture: 7→128→128→4 */
/* Actor Architecture: (7+4)→256→256→2 */
/* Total weights: ~{total_params} parameters */
"""
    (out_dir / "stm32_model_info.h").write_text(info, encoding="utf-8")

    print(f"Export complete → {out_dir}/")
    for f in out_dir.iterdir():
        print(f"  {f.name}: {f.stat().st_size} bytes")
